### ISSUE TITLE
Error when editing activities

### ISSUE THREAD

**Issue by Cookierock** [Confluente/backend#27]
I get an error if I click 'save' when editing an activity 🙃
Occurs for every activity. Are you able to replicate this?
I'm using the current backend + frontend master branches.

The first lines of console log:
`Unhandled rejection TypeError: Cannot read property 'length' of null`
`at Object.stringifyArrayOfStrings ([...]\backend\arrayHelper.js:9:19)`
`[...]`

**Comment by rdvhoorn** [comment]
I cannot replicate this error. Could you regenerate your database and check again? If the error reoccurs can you specify what exactly you are doing? Which activity on the standard import_initial database, or if you had to create an activity to recreate, what the specifics of that activity are?

**Comment by Cookierock** [comment]
[**Made a video of the replication**](https://drive.google.com/open?id=1qx9vZDR1RdWrGQClUJm1dhXIarotSkw6)

I re-initialized the database using import_initial. I'm only able to replicate the error when creating a new event.

**Required steps:**
1. Create a new event. I am able to replicate the error with both minimum input and all the fields filled in.
2. Save the event.
3. Edit the event. I have successfully tested and replicated the error when no value had been changed in the edit, as well as changing the participation fee. However, it could be possible that this applies to any value change.
4. Save the event. This does _not_ change any value, and instead returns the following error in the console log:

```
Unhandled rejection TypeError: Cannot read property 'length' of null
    at Object.stringifyArrayOfStrings (C:\[...]\backend\arrayHelper.js:9:19)
    at C:\[...]\backend\routes\activities.js:250:55
    at tryCatcher (C:\[...]\backend\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\[...]\backend\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\[...]\backend\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\[...]\backend\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\[...]\backend\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\[...]\backend\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\[...]\backend\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\[...]\backend\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\[...]\backend\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```

Using Firefox 74.0 on Windows 10 Enterprise Build 1904.
